"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var git_1 = require("./git");
exports.getLatestTag = git_1.getLatestTag;
var shell_1 = require("./shell");
exports.exec = shell_1.exec;
exports.sanitizeOutput = shell_1.sanitizeOutput;
exports.SHELL_EXEC_OPTIONS = shell_1.SHELL_EXEC_OPTIONS;
exports.SHELL_EXEC_RETURN_ARRAY = shell_1.SHELL_EXEC_RETURN_ARRAY;
exports.SHELL_EXEC_RETURN_STRING = shell_1.SHELL_EXEC_RETURN_STRING;
